### PR TITLE
Add ACS 4.17 support

### PR DESCRIPTION
**Pull request by Pearl1594**

### CODE REVIEW

**Comment by davidjumani** [comment]
@Pearl1594 You may wanna test / update the testdata to ensure that it hasn't changed in 4.17

**Comment by Pearl1594** [comment]
Yes, was going to spend some time on that, hence was marked as a draft PR.

**Comment by vdombrovski** [comment]
Hello, I've created a PR which fixes Icon type behavior in 4.17: https://github.com/apache/cloudstack-go/pull/45.

**Comment by rohityadavcloud** [comment]
cc @shwstppr may need rework or latest api json for use to generate the bindings against 4.17.2

**Comment by mlsorensen** [comment]
With the release of 4.18, do we want to just move forward with updating for that instead @rohityadavcloud ?

**Comment by shwstppr** [comment]
@mlsorensen cc @mlsorensen is it okay if merge this and add a release for 4.17 support and then work for 4.18 release?

**Review by shwstppr — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
Lgtm

**Pull request merged**
