### PR TITLE
Implement resourceiconresponse as interface{}

### PR DESCRIPTION
**Pull request by vdombrovski**
All "icon" fields are set to be of resourceiconresponse type, however that type is not defined anywhere, making the icon field resolving to a string.

This isn't correct as ACS returns the Icon as an object, which in term causes these types of error:

```sh
json: cannot unmarshal object into Go struct field VirtualMachinesMetric.virtualmachine.icon of type string
```

This change sets the type of resourceiconresponse type to be an empty interface{}, to guarantee some backward compatibility and ensure that the unmarshalling works as intended.

Tested againt ACS 4.17.1

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
cc @davidjumani @shwstppr can you assist?

**Comment by vdombrovski** [comment]
Btw I know this is out of scope as ACS 4.17 support is still drafted here https://github.com/apache/cloudstack-go/pull/38, but some repos downstream depend on this change (in my case https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack)

**Review by shwstppr — APPROVED** [review]

**Review by davidjumani — APPROVED** [review]

**Comment by shwstppr** [comment]
Merging based on approvals

**Comment by yelbom** [comment]
🤷‍♂️

**Pull request merged**
