### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by jbampton**

### CODE REVIEW

**Comment by soreana** [comment]
@rohityadavcloud I will take care of this. I'm updating the domainid description, I would add these as well.

Checkout the following pr please:
https://github.com/apache/cloudstack/issues/7776

**Comment by soreana** [comment]
Btw, I don't have a permission to assign PRs in this repository, feel free to assign this PR to me.

**Comment by soreana** [comment]
@jbampton I've added the changes in the [generate/listApis.json](https://github.com/apache/cloudstack-go/pull/64#diff-9ab30883c5e2c6c57310693016338a137804420ae69a135e15aa57a5f7cd18bd) file to the PR https://github.com/apache/cloudstack/pull/7876, can you please exclude them from your PR?

**Comment by soreana** [comment]
@rohityadavcloud My PR got merged, I would like to update the generated.go file but I couldn't find any docs about it. This is the only thing I found :D 

> The SDK relies on the  generate.go script to auto generate the code for all the supported APIs listed in the listApis.json file. The listAPIs.json file holds the output of listApis command for a specific release of CloudStack.

```
# Run it via the Makefile
make all
```

**Comment by DaanHoogland** [comment]
@soreana @rohityadavcloud if listApis.json is generated, should it be in the repository? As opposed to the generation script/command I mean.

@jbampton can you remove the file from your PR, please?

**Comment by soreana** [comment]
> @soreana @rohityadavcloud if listApis.json is generated, should it be in the repository? As opposed to the generation script/command I mean.
> 
> @jbampton can you remove the file from your PR, please?

@DaanHoogland I'm not sure why they're there. I suppose the generated files are bundled so that the SDK knows what API calls are available.

**Comment by DaanHoogland** [comment]
I understand @soreana , but I'd expect it to be generated on build- or run-time. Maybe we can improve it that way?

**Pull request merged**
