### PR TITLE
add +30 more apis

### PR DESCRIPTION
**Pull request by ahmedali6**
This merge requests adds support to the following APIs:

### VirtualMachineService

- `importVm`
- `unmanageVirtualMachine`
- `listUnmanagedInstances`
- `importUnmanagedInstance`
- `createVMSchedule`
- `updateVMSchedule`
- `listVMSchedule`
- `deleteVMSchedule `

### ZoneService

- `listVmwareDcVms`
- `addVmwareDc`
- `listVmwareDcs`
- `updateVmwareDc`
- `removeVmwareDc`

### UserService

- `listUserData`
- `deleteUserData`
- `registerUserData`
- `moveUser`
- `setupUserTwoFactorAuthentication`

### ProjectService

- `createProjectRole`
- `updateProjectRole`
- `deleteProjectRole`

### RoleService

- `listProjectRoles`

### ObjectStoreService

- `createBucket`
- `deleteBucket`
- `updateBucket`
- `listBuckets`

### HostService

- `migrateSecondaryStorageData`
- `cancelHostAsDegraded`
- `listHostHAProviders`
- `listSecondaryStorageSelectors`
- `createSecondaryStorageSelector`
- `removeSecondaryStorageSelector`
- `listHostHAResources`
- `declareHostAsDegraded`
- `updateSecondaryStorageSelector`

### StoragePoolService

- `listObjectStoragePools`
- `listStoragePoolObjects`
- `updateObjectStoragePool`
- `addObjectStoragePool`
- `deleteObjectStoragePool`
- `listStoragePoolsMetrics`

### OauthService

- `listOauthProvider`
- `updateOauthProvider`
- `deleteOauthProvider`

### RegistrationService

- `registerOauthProvider`

### ShutdownService

- `readyForShutdown`

### VolumeService

- `listVolumesUsageHistory`
- `assignVolume`

### TemplateService

- `linkUserDataToTemplate`

### GuestOSService

- `getHypervisorGuestOsNames`

### ImageStoreService

- `listImageStoreObjects`
- `updateImageStore`
- `downloadImageStoreObject`

### PodService

- `updatePodManagementNetworkIpRange`

### ConfigurationService

- `updateStorageCapabilities`

### CertificateService

- `listCAProviders`
- `provisionCertificate`

### DiagnosticsService

- `getDiagnosticsData`

### MetricsService

- `listInfrastructure`

### ManagementService
 - `listManagementServers`

### CODE REVIEW

**Comment by ahmedali6** [comment]
@vishesh92

**Review by vishesh92 — APPROVED** [review]
clgtm.

**Comment by ahmedali6** [comment]
@vishesh92 @rohityadavcloud Can this be merged?

**Review by Pearl1594 — APPROVED** [review]
code build ran fine. LGTM

**Pull request merged**
