### PR TITLE
Restore methods with optional params for 4.19 compatability

### PR DESCRIPTION
**Pull request by vishesh92**
Add optional params from https://github.com/apache/cloudstack-go/pull/77 to the `requiredParams.go`.

### CODE REVIEW

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Comment by weizhouapache** [comment]
@vishesh92 
clustertype is always an optional parameter, right? 
In the official ACS/cloudstack-go releases I mean.

**Comment by weizhouapache** [comment]
I checked the diff betwen this PR and latest v2.15.0

1. guest OS (**_no need to fix I think_**)

```
 type GuestOSServiceIface interface {
        AddGuestOs(p *AddGuestOsParams) (*AddGuestOsResponse, error)
-       NewAddGuestOsParams(details map[string]string, oscategoryid string, osdisplayname string) *AddGuestOsParams
+       NewAddGuestOsParams(oscategoryid string, osdisplayname string) *AddGuestOsParams
        AddGuestOsMapping(p *AddGuestOsMappingParams) (*AddGuestOsMappingResponse, error)

...
-       NewUpdateGuestOsParams(details map[string]string, id string, osdisplayname string) *UpdateGuestOsParams
+       NewUpdateGuestOsParams(id string, osdisplayname string) *UpdateGuestOsParams

```

2. CKS

```
diff --git a/cloudstack/KubernetesService.go b/cloudstack/KubernetesService.go
index 07bcd3e..4dcf1f1 100644
--- a/cloudstack/KubernetesService.go
+++ b/cloudstack/KubernetesService.go
@@ -31,7 +31,7 @@ type KubernetesServiceIface interface {
        AddKubernetesSupportedVersion(p *AddKubernetesSupportedVersionParams) (*AddKubernetesSupportedVersionResponse, error)
        NewAddKubernetesSupportedVersionParams(mincpunumber int, minmemory int, semanticversion string) *AddKubernetesSupportedVersionParams
        CreateKubernetesCluster(p *CreateKubernetesClusterParams) (*CreateKubernetesClusterResponse, error)
-       NewCreateKubernetesClusterParams(description string, kubernetesversionid string, name string, serviceofferingid string, size int64, zoneid string) *CreateKubernetesClusterParams
+       NewCreateKubernetesClusterParams(clustertype string, name string, zoneid string) *CreateKubernetesClusterParams
        DeleteKubernetesCluster(p *DeleteKubernetesClusterParams) (*DeleteKubernetesClusterResponse, error)
        NewDeleteKubernetesClusterParams(id string) *DeleteKubernetesClusterParams
        DeleteKubernetesSupportedVersion(p *DeleteKubernetesSupportedVersionParams) (*DeleteKubernetesSupportedVersionResponse, error)


```

**Review by rohityadavcloud — APPROVED** [review]

**Review by weizhouapache — APPROVED** [review]
checked the diff between v2.15.0 and this PR, did not find other compatibility issues except the guest OS

I think it is good to merge. @vishesh92 thanks

**Pull request merged**
