### PR TITLE
4.19 support changes

### PR DESCRIPTION
**Pull request by shwstppr**
For cutting 4.19 support release

### CODE REVIEW

**Comment by shwstppr** [comment]
@Pearl1594 @rohityadavcloud @vishesh92 If you approve, we can merge and create a new release

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Comment by rohityadavcloud** [comment]
LGTM - didn't test it. Are there basic build/tests that cover basic checks?

**Comment by shwstppr** [comment]
Tests are passing both locally and in GH action

**Comment by rohityadavcloud** [comment]
LGTM - merged @shwstppr

**Pull request merged**
