### PR TITLE
add api call createConsoleEndpoint

### PR DESCRIPTION
**Pull request by sbrueseke**

### CODE REVIEW

**Comment by sbrueseke** [comment]
@weizhouapache @rohityadavcloud can you please review this PR?

**Comment by rohityadavcloud** [comment]
ping @shwstppr @vishesh92 can you review and advise on this PR, thanks. @sbrueseke has advised me privately that they need this for some use with the cloudstack packer plugin.

**Review by shwstppr — APPROVED** [review]
LGTM

**Review by weizhouapache — COMMENTED** [review]
code lgtm

**Review by vishesh92 — APPROVED** [review]
clgtm

**Pull request merged**
