### PR TITLE
WIP: (#36) - support async client

### PR DESCRIPTION
**Pull request by tetra12**
solves #36 

1. Add a draft of an async request wrapper

TBD:
1. Regenerate all APIs to deploy an async client
2. Update the generator template
3. Add async test

### CODE REVIEW

**Comment by nvazquez** [comment]
Hi @davidjumani @Pearl1594 could you please review this?

**Comment by davidjumani** [comment]
@tetra12 A better implementation would be to modify `GetAsyncJobResult` and implement channels over there rather than creating a wrapper for the request. The AsyncTimeout is while waiting for an async job, ie: if the first job is a sync job it waits for it and then times out waiting for the async job to complete. To set a timeout for any call, use the `cs.Timeout` method

**Comment by rohityadavcloud** [comment]
Closing/re-opening PR to rekick CI

**Comment by rohityadavcloud** [comment]
ping @tetra12 @davidjumani - any update on this? thanks.

**Comment by tetra12** [comment]
This refactor is NOT required, since  current API implements both async and timeout:
```go
func NewClient() *cloudstack.CloudStackClient {
	cs := cloudstack.NewAsyncClient(apiURL, apiKey, secretKey, false)
	cs.AsyncTimeout(acsTimeout)
	return cs
}
```
Closing as invalid

**Pull request closed without merging**
