### PR TITLE
Support 4.x compatibility

### PR DESCRIPTION
**Pull request by davidjumani**
Modded version of https://github.com/apache/cloudstack-go/pull/21

Allows backward compatibility of Managementserverid of both int64 and string data types

### CODE REVIEW

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@davidjumani how have we tested this? (apart from the unit test)

**Comment by davidjumani** [comment]
@rhtyd Yes, ran a couple of tests targetting the ManagementServerId with both int and string data types in the response JSON

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Comment by rhtyd** [comment]
Alright @psycofdj @davidjumani thanks for coming to some solution that satisfies both your requirements.

**Pull request merged**
